### ISSUE TITLE
Project link doesn't work when clicking in folium map.

### ISSUE THREAD

**Issue by vnoelifant** [vnoelifant/charity-finder#46]
Only able to view "Project Details" in the folium map when viewing link in a new tab.

**Comment by vnoelifant** [comment]
When hovering over a heatmap area, in the popup, View Project Details link does not open from popup. 

![Image](https://github.com/vnoelifant/charity-finder/assets/43191157/1c1a08b3-fe97-470c-9f43-e7dbce69568a)

**Comment by vnoelifant** [comment]
Here are resources I have found and read about.  I included the iframe code which I thought would work, but others recommend some type of javascript code since folium may not be able to handle events within the popup itself. 

https://stackoverflow.com/questions/74707544/add-a-clickevent-function-to-multiple-folium-markers-with-python

https://github.com/python-visualization/folium/issues/13

https://gis.stackexchange.com/questions/385565/inserting-an-url-link-in-markers-popup-in-folium

https://stackoverflow.com/questions/29535715/python-with-folium-how-can-i-embed-a-webpage-in-the-popup

https://gis.stackexchange.com/questions/385565/inserting-an-url-link-in-markers-popup-in-folium

https://www.515tech.com/post/mapping-global-terrorism-with-folium-and-publicly-available-data

**Comment by bbelderbos** [comment]
Seems adding `target=_blank` to the link (a tag) works here :)
Please confirm on your end ... (hope you won't hit an ad popup blocker in your browser / windows ...)
